import type { Metadata } from "next";
<<<<<<< HEAD
<<<<<<< HEAD
import { Geist } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/app/theme-provider";

const geistSans = Geist({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "DSC NITH",
  description: "Developer Students Club NIT Hamirpur",
=======
import { Geist, Geist_Mono } from "next/font/google";
=======
import { Geist } from "next/font/google";
>>>>>>> 4cbbff7 (huh Shlok)
import "./globals.css";
import { ThemeProvider } from "@/components/app/theme-provider";
import Navbar from "@/components/app/navbar/navbar";

const geistSans = Geist({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
<<<<<<< HEAD
  title: "Create Next App",
  description: "Generated by create next app",
>>>>>>> 5c48a6b (next initialised)
=======
  title: "DSC NITH",
  description: "Developer Students Club NIT Hamirpur",
>>>>>>> 4cbbff7 (huh Shlok)
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> 4cbbff7 (huh Shlok)
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.className}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
<<<<<<< HEAD
          {children}
        </ThemeProvider>
=======
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
>>>>>>> 5c48a6b (next initialised)
=======
          <Navbar />
          {children}
        </ThemeProvider>
>>>>>>> 4cbbff7 (huh Shlok)
      </body>
    </html>
  );
}
